feat: multi-treasury transfer contract RNSCommission
axieinfinity/rns-contracts pull request #217
Opened 2024-06-03 07:28 UTC by tringuyenskymavis

### Description
This PR creates an RNSCommission contract for multi-treasury transfer.

2024-06-03 10:22 UTC, TuDo1403 requested changes

2024-06-03 10:22 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  }
`fallback` is not needed.

2024-06-03 10:22 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  mapping(address => bool) public _allowedSenders;
```suggestion
  mapping(address sender => bool allowed) public _allowedSenders;
```

2024-06-03 10:22 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  }
how can we unset specific sender?

2024-06-03 10:22 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  bytes32 public constant COMMISSION_SETTER_ROLE = keccak256("COMMISSION_SETTER_ROLE");
missing doc

2024-06-03 10:22 UTC, TuDo1403 commented on src/interfaces/INSCommission.sol
> +  event TreasuryInfoUpdated(address payable treasuryAddr, bytes name, uint256 treasuryId);
```suggestion
  /// @dev Emitted when all the treasury info info are updated.
  event TreasuriesUpdated(address indexed updatedBy, Commission[] treasuriesInfo);
  /// @dev Emitted when specific treasury info are updated.
  event TreasuryInfoUpdated(address indexed updatedBy, address payable treasuryAddr, bytes name, uint256 treasuryId);
```

2024-06-03 10:22 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    if (_isAllowedSender(msg.sender)) {
what if sender is not allowed?

2024-06-03 10:22 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    if (treasuryId < 0 || treasuryId > _commissionInfo.length - 1) {
`treasuryId` never < 0

2024-06-03 10:23 UTC, TuDo1403 requested changes

2024-06-03 10:23 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  Commission[] internal _commissionInfo;
```suggestion
  Commission[] internal _commissionInfos;
```

2024-06-03 10:23 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  mapping(address => bool) public _allowedSenders;
```suggestion
  mapping(address => bool) public _allowedSender;
```

2024-06-03 10:26 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    uint256 sum = 0;
```suggestion
    uint256 sum;
```

2024-06-03 10:27 UTC, ducthotran2010 requested changes
Consider fixing the issues I mentioned in the last PR

2024-06-03 10:27 UTC, ducthotran2010 commented on src/RNSCommission.sol
> +  }
Can we use `_allowedSenders[sender]` directly?

2024-06-03 10:27 UTC, ducthotran2010 commented on src/RNSCommission.sol
> +    }
Don't repeat yourself: https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

2024-06-03 10:27 UTC, ducthotran2010 commented on src/RNSCommission.sol
> +  function getTreasuries() external view returns (Commission[] memory treasuriesInfo) {
```suggestion
  function getCommissions() external view returns (Commission[] memory treasuriesInfo) {
```

2024-06-03 10:27 UTC, ducthotran2010 commented on src/RNSCommission.sol
> +  function changeTreasuryInfo(address payable newAddr, bytes calldata name, uint256 treasuryId)
```suggestion
  function changeTreasuryInfo(uint256 treasuryId, address payable newAddr, bytes calldata name)
```

2024-06-03 10:27 UTC, ducthotran2010 commented on src/interfaces/INSCommission.sol
> +  function changeTreasuryInfo(address payable newAddr, bytes calldata name, uint256 treasuryId) external;
- [change](https://www.etymonline.com/search?q=change): to make (something) other than what it was, cause to turn or pass from one state to another
- [set](https://www.etymonline.com/search?q=set): put in a definite place
```suggestion
  function setTreasuryInfo(uint256 treasuryId, address payable newAddr, bytes calldata name) external;
```

2024-06-03 10:27 UTC, ducthotran2010 commented on src/RNSCommission.sol
> +    if (treasuryId < 0 || treasuryId > _commissionInfo.length - 1) {
Since treasuryId is uint256, it cannot be < 0

2024-06-03 10:27 UTC, ducthotran2010 commented on src/RNSCommission.sol
> +      allocs[lastIdx] = Allocation({ recipient: _commissionInfo[lastIdx].recipient, value: totalAmount - sumValue });
This code replaces value of the last recipient

2024-06-03 10:28 UTC, ducthotran2010 commented on src/interfaces/INSCommission.sol
> +  event TreasuryInfoUpdated(address payable treasuryAddr, bytes name, uint256 treasuryId);
`uint256 indexed treasuryId`

2024-06-04 09:55 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    if (length < 1) revert InvalidArrayLength();
```suggestion
    if (length == 0) revert InvalidArrayLength();
```

2024-06-04 09:55 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    for (uint256 i = 0; i < length; ++i) {
```suggestion
    for (uint256 i; i < length; ++i) {
```

2024-06-04 09:56 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    for (uint256 i = 0; i < length; ++i) {
v

2024-06-04 10:11 UTC, TuDo1403 commented on src/interfaces/INSCommission.sol
> +    bytes name; // Treasury's name
```suggestion
    bytes name; // Treasury's name
```
not need

2024-06-05 06:24 UTC, nxqbao approved these changes, later dismissed

2024-06-05 06:28 UTC, ducthotran2010 approved these changes, later dismissed
minor:
* treasury name
* commission <> treasury

2024-06-06 04:02 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  Commission[] internal _commissionInfos;
should provide doc

2024-06-06 04:03 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    }
```suggestion
    if (totalAmount == 0) revert InvalidAmountOfRON();
```

2024-06-06 04:04 UTC, TuDo1403 commented on src/RNSCommission.sol
> +      address payable recipient = allocs[i].recipient;
I don't see why we should cache those value to stack.

2024-06-06 04:16 UTC, TuDo1403 requested changes

2024-06-06 04:16 UTC, TuDo1403 commented on src/interfaces/INSCommission.sol
> +    uint256 value;
this is not `value`. Renamed to something else, for example `feeBps`

2024-06-06 04:19 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    _setRoleAdmin(SENDER_ROLE, COMMISSION_SETTER_ROLE);
this is not needed.

2024-06-06 04:20 UTC, TuDo1403 commented on src/RNSCommission.sol
> +    if (commissionIdx > _commissionInfos.length - 1) {
```suggestion
    if (commissionIdx >= _commissionInfos.length) {
```

2024-06-06 04:22 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  bytes32 public constant COMMISSION_SETTER_ROLE = keccak256("COMMISSION_SETTER_ROLE");
I don't think `COMMISSION_SETTER_ROLE` is needed.

2024-06-06 04:23 UTC, TuDo1403 commented on src/RNSCommission.sol
> +      RONTransferHelper.safeTransfer(recipient, value);
should emit event when allocate to treasury

2024-06-06 04:25 UTC, TuDo1403 commented on src/RNSCommission.sol
> +  bytes32 public constant SENDER_ROLE = keccak256("SENDER_ROLE");
this also should have declarations in interface.

2024-06-06 08:52 UTC, TuDo1403 commented on src/interfaces/INSCommission.sol
> +  event Transfer(address indexed recipient, uint256 commissionAmount);
```suggestion
  event Distributed(address indexed recipient, uint256 commissionAmount);
```

2024-06-06 08:59 UTC, TuDo1403 approved these changes, later dismissed
LGTM. Please make sure the logic is propoperly tested.

2024-06-06 09:49 UTC, TuDo1403 approved these changes

2024-06-24 09:45 UTC, TuDo1403 commented
Closed in favor of #220

2024-06-24 09:45 UTC, closed without merging